openapi: 3.0.0
info:
  description: Backend API for the Stanford digital repository
  version: 1.0.0
  title: DOR Services API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /resources:
    post:
      summary: Register a new object
      operationId: 'objects#create'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestDRO'
      responses:
        '201':
          description: Created
components:
  schemas:
    Title:
      description: A title.
      type: object
      additionalProperties: false
      properties:
        value:
          description: String or integer value of the descriptive element.
          oneOf:
          - type: string
          - type: integer
    RequestDRO:
      description: A request to create a resource.
      type: object
      properties:
        title:
          $ref: '#/components/schemas/Title'
